### ISSUE TITLE
Images names should correspond to image_id

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/ohioColeo#1]
Currently the name given to each image corresponds to its `occurrence_id`, i.e. the occurrence record insert at time of photo upload. Instead, it should correspond to the insert id, i.e. primary key, of the photo in the `images` table.

**Comment by cambro** [comment]
note that the join table occurrences_images is present for this purpose

**Comment by cambro** [comment]
It's possible this is not fixed everywhere. see references to all `photo_id` 
For example, in /routes/upload.js:
`var photo_id = occurrence_id`

Opened to make sure we double check.
