### ISSUE TITLE
Family as base unit in browse/search

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/ohioColeo#2]
Instead of occurrences being the base unit in the browse and search view, families should be. Each row should show the name of a family and the number of occurrences of that family, with the option to expand that view and show all occurrences in that family.

**Comment by jczaplew** [comment]
Does it make sense to maintain family as the base unit even when various filters are applied?

**Comment by cambro** [comment]
I think that the default behavior to summarize by family is the right way to go. A search for a genus would return only one family, but a consistent interface makes sense
