### ISSUE TITLE
check integrity of session/user management

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/ohioColeo#20]
There is a possible bug related to partial data entry and/or session handling. Users have reported errors like: I went to log out and got “503 something went wrong” error. Other usual behavior possibly related to their browser cache behavior and/or session handling.

**Comment by jczaplew** [comment]
I'll have to look into this a little more, but I'd guess it might happen when someone logs in, the application crashes, and then they try to log out.

**Comment by jczaplew** [comment]
Also, did they mention something specific about partial data entry and logging out?

**Comment by cambro** [comment]
It is not apparent what they were doing. I suspect local browser caching of some sort of weird state.
