### ISSUE TITLE
Broken link to css in views

### ISSUE THREAD

**Issue by shogsten** [UW-Macrostrat/ohioColeo#31]
The following link is broken in views/occurences.html, views/family.html, views/mybeetles.html
GET /bower_components/leaflet.markerclusterer/dist/Markercluster.css 
GET /bower_components/leaflet.markerclusterer/dist/Markercluster.Default.css

The link should be 
GET /bower_components/leaflet.markerclusterer/dist/MarkerCluster.css 
GET /bower_components/leaflet.markerclusterer/dist/MarkerCluster.Default.css

**Comment by jczaplew** [comment]
See explanation here - https://github.com/UW-Macrostrat/ohioColeo/pull/32
